logsBucket: 'gs://cloudbuild-logs-data-ops-466417'
timeout: 1200s

steps:
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['init']
    dir: 'terraform'
    
  #  Destrói recursos antes de recriar, evitando conflitos de existência
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['destroy', '-auto-approve']
    dir: 'terraform'

  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['plan', '-out=tfplan']
    dir: 'terraform'

  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve', 'tfplan']
    dir: 'terraform'