substitutions:
  _PROJECT_ID: 'data-ops-466417'
  
logsBucket: 'gs://cloudbuild-logs-data-ops-466417'
timeout: 1200s

steps:
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['init']
    dir: 'terraform'

  # Step para importar recursos existentes
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    dir: 'terraform'
    args:
      - '-c'
      - |
        terraform state list | grep google_storage_bucket.tf_composer_bucket || terraform import google_storage_bucket.tf_composer_bucket tf-composer-bucket
        terraform state list | grep google_storage_bucket.tf_cloud_functions_bucket || terraform import google_storage_bucket.tf_cloud_functions_bucket tf-cloud-functions-bucket
        terraform state list | grep google_storage_bucket.tf_bigquery_scripts_bucket || terraform import google_storage_bucket.tf_bigquery_scripts_bucket tf-bigquery-scripts-bucket
        terraform state list | grep google_compute_network.composer_prod_network || terraform import google_compute_network.composer_prod_network projects/$PROJECT_ID/global/networks/composer-prod-network

  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['plan', '-out=tfplan']
    dir: 'terraform'

  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve', 'tfplan']
    dir: 'terraform'