substitutions:
  _PROJECT_ID: 'data-ops-466417'

logsBucket: 'gs://cloudbuild-logs-data-ops-466417'
timeout: 3600s

steps:

  # 1. Terraform Init
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['init']
    dir: 'terraform'

  # 2. Importar recursos existentes (se necessário)
  # - name: 'hashicorp/terraform:latest'
  #   entrypoint: 'sh'
  #   dir: 'terraform'
  #   args:
  #     - '-c'
  #     - |
  #       terraform state list | grep google_storage_bucket.tf_composer_bucket || terraform import google_storage_bucket.tf_composer_bucket tf-composer-bucket
  #       terraform state list | grep google_storage_bucket.tf_cloud_functions_bucket || terraform import google_storage_bucket.tf_cloud_functions_bucket tf-cloud-functions-bucket
  #       terraform state list | grep google_storage_bucket.tf_bigquery_scripts_bucket || terraform import google_storage_bucket.tf_bigquery_scripts_bucket tf-bigquery-scripts-bucket
  #       terraform state list | grep google_compute_network.composer_prod_network || terraform import google_compute_network.composer_prod_network projects/$PROJECT_ID/global/networks/composer-prod-network
  #       terraform state list | grep google_compute_subnetwork.composer_prod_subnetwork || terraform import google_compute_subnetwork.composer_prod_subnetwork projects/$PROJECT_ID/regions/southamerica-east1/subnetworks/composer-prod-subnetwork
  #       terraform state list | grep google_compute_global_address.composer_private_ip_range || terraform import google_compute_global_address.composer_private_ip_range projects/$PROJECT_ID/global/addresses/composer-private-ip-range

  # 3. Planejar destruição
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['plan', '-destroy', '-out=tfplan_destroy']
    dir: 'terraform'

  # 4. Aplicar destruição
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve', 'tfplan_destroy']
    dir: 'terraform'

  # 5. Novo plano após destruição
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['plan', '-out=tfplan']
    dir: 'terraform'

  # 6. Aplicar criação
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve', 'tfplan']
    dir: 'terraform'
