substitutions:
  _PROJECT_ID: 'data-ops-466417'

logsBucket: 'gs://cloudbuild-logs-data-ops-466417'
timeout: 7200s

steps:
  # 1. Terraform Init
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['init']
    dir: 'terraform'

  # 2. Importar recursos existentes
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    dir: 'terraform'
    args:
      - '-c'
      - |
        terraform state list | grep google_storage_bucket.tf_composer_bucket || terraform import google_storage_bucket.tf_composer_bucket tf-composer-bucket
        terraform state list | grep google_storage_bucket.tf_cloud_functions_bucket || terraform import google_storage_bucket.tf_cloud_functions_bucket tf-cloud-functions-bucket
        terraform state list | grep google_storage_bucket.tf_bigquery_scripts_bucket || terraform import google_storage_bucket.tf_bigquery_scripts_bucket tf-bigquery-scripts-bucket
        terraform state list | grep google_compute_network.prod_network || terraform import google_compute_network.prod_network projects/data-ops-466417/global/networks/prod-network
        terraform state list | grep google_compute_subnetwork.prod_subnetwork || terraform import google_compute_subnetwork.prod_subnetwork projects/data-ops-466417/regions/southamerica-east1/subnetworks/prod-subnetwork
        terraform state list | grep google_compute_global_address.private_ip_range || terraform import google_compute_global_address.private_ip_range projects/data-ops-466417/global/addresses/private-ip-range
        terraform state list | grep google_compute_router.nat_router || terraform import google_compute_router.nat_router projects/data-ops-466417/regions/southamerica-east1/routers/prod-nat-router
        terraform state list | grep google_compute_router_nat.nat_config || terraform import google_compute_router_nat.nat_config projects/data-ops-466417/regions/southamerica-east1/routers/prod-nat-router/nat/prod-nat
  
  # 3. Planejar criação
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['plan', '-out=tfplan']
    dir: 'terraform'

  # 4. Aplicar criação
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve', 'tfplan']
    dir: 'terraform'